security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
      

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/
            stateless: true
            jwt: ~

    access_control:
        
        # Public Access
        - { path: ^/api/login,                  roles: PUBLIC_ACCESS }
        - { path: ^/api/categories$,            roles: PUBLIC_ACCESS }
        - { path: ^/api/sub_categories$,        roles: PUBLIC_ACCESS }
        - { path: ^/api/posts$,                 roles: PUBLIC_ACCESS }
        - { path: ^/api/categories$,            roles: PUBLIC_ACCESS, methods: GET }
        - { path: ^/api/categories/[0-9]+$,     roles: PUBLIC_ACCESS, methods: GET }
        - { path: ^/api/posts/[0-9]+$,          roles: PUBLIC_ACCESS, methods: GET }
        - { path: ^/api/answers$,               roles: PUBLIC_ACCESS, methods: GET }
        - { path: ^/api/answers/[0-9]+$,        roles: PUBLIC_ACCESS, methods: GET }
        
        # Only Admin
        - { path: ^/api/users$,                 roles: IS_AUTHENTICATED_FULLY, methods: GET }
        - { path: ^/api/categories$,            roles: IS_AUTHENTICATED_FULLY, methods: POST }
        - { path: ^/api/categories/[0-9]+$,     roles: IS_AUTHENTICATED_FULLY, methods: PUT}
        - { path: ^/api/categories/[0-9]+$,     roles: IS_AUTHENTICATED_FULLY, methods: POST }
        - { path: ^/api/categories$,            roles: IS_AUTHENTICATED_FULLY, methods: POST }
        - { path: ^/api/sub_categories/[0-9]+$, roles: IS_AUTHENTICATED_FULLY, methods: PUT }
        - { path: ^/api/sub_categories/[0-9]+$, roles: IS_AUTHENTICATED_FULLY, methods: POST }
        - { path: ^/api/sub_categories/[0-9]+$, roles: IS_AUTHENTICATED_FULLY, methods: GET }

        # Admin / User 
        - { path: ^/api/home$,                  roles: [IS_AUTHENTICATED_FULLY, ROLE_USER] }
        - { path: ^/api/posts$,                 roles: [IS_AUTHENTICATED_FULLY, ROLE_USER], methods: POST }
        - { path: ^/api/answers$,               roles: [IS_AUTHENTICATED_FULLY, ROLE_USER], methods: ['GET', 'POST'] }

        # Admin + User qui a crée le post, à voir ...
        - { path: ^/api/posts/[0-9]+$,          roles: [IS_AUTHENTICATED_FULLY, ROLE_USER], methods: POST }
        - { path: ^/api/posts/[0-9]+$,          roles: [IS_AUTHENTICATED_FULLY, ROLE_USER], methods: PUT }
        - { path: ^/api/posts/[0-9]+/resolu$,   roles: [IS_AUTHENTICATED_FULLY, ROLE_USER], methods: 'POST' }
        - { path: ^/api/answers/[0-9]+$,        roles: [IS_AUTHENTICATED_FULLY, ROLE_USER], methods: ['GET', 'POST', 'PUT'] }
        - { path: ^/api/answers/[0-9]+$,        roles: [IS_AUTHENTICATED_FULLY, ROLE_USER], methods: 'POST' }
        